### ISSUE TITLE
Add JSON file dialog

### ISSUE THREAD

**Issue by Mrgts411** [grengine/modeler#1]
this is not an issue/bug, it's more of a request.

can you please add a file dialog to load/save JSON?

like this: http://image.prntscr.com/image/123aee2ee3574e5ea2f9d84fe44f34f0.png

thanks!

**Comment by Enveed** [comment]
sure! It's in the next version (1.1-3)! :)

**Comment by Enveed** [comment]
The feature is now implemented in the way I stated above.
