### ISSUE TITLE
Can't find Vanilla MC .json files for import [Tutorial Needed]

### ISSUE THREAD

**Issue by Vic497** [grengine/modeler#3]
Heya GRengine! I saw this free app on github and I thought it would be awesome for modding, but I hsve no idea on how to use it. At all. Also, I am unable to find individual .json files for the vanilla models, like armor & weapons. Pls help.

-Vic

**Note - I'm using a Macbook Air

**Comment by Mrgts411** [comment]
you don't find a json, you create it.

you need to set the textures of the item first, then you start working on 3d modeling it.

**Comment by Vic497** [comment]
Alright, I'll try to do that after I find a tutorial on how to make armour. Thanks!
